### ISSUE TITLE
DTO 생성자 변경

### ISSUE THREAD

**Issue by LeeSM0518** [sjsage522/comunity#1]
https://github.com/sjsage522/comunity/blob/bd4a4cdeab2134d95b80fc4cf789dde1b727f326/src/main/java/com/example/comunity/controller/CommentController.java#L111

DTO를 생성할 때, comment로부터 getter를 호출해서 값을 넘기는것이 아니라 comment 인스턴스 자체를 넘기는 코드로 변경해주세요.
훨씬 코드가 깔끔해지고 나중에 Comment에 속성이 늘어났을 때 Comment 클래스만 변경하면 되서 좋을 것 같아요.
그리고 DTO 생성하는 부분들을 다 이러한 방식으로 리팩토링 해주세요.

**Comment by sjsage522** [comment]
리팩토링 완료했습니다.
