### ISSUE TITLE
Repository 의존 관계 수정

### ISSUE THREAD

**Issue by LeeSM0518** [sjsage522/comunity#2]
https://github.com/sjsage522/comunity/blob/bd4a4cdeab2134d95b80fc4cf789dde1b727f326/src/main/java/com/example/comunity/repository/BoardRepository.java#L34

해당 delete 메서드를 구현하려고 BoardRepository가 여러 Repository를 의존하고 있어서 의존 관계가 이상하고
BoardRepository가 Service 역할까지 하고 있게 됩니다.
게시판 내의 여러개의 첨부파일을 batch delete하는 로직은 Service 계층에서 해주는게 좋을 것 같아요.

**Comment by sjsage522** [comment]
리팩토링 완료했습니다.
