### ISSUE TITLE
Board 수정 메서드 변경

### ISSUE THREAD

**Issue by LeeSM0518** [sjsage522/comunity#3]
https://github.com/sjsage522/comunity/blob/bd4a4cdeab2134d95b80fc4cf789dde1b727f326/src/main/java/com/example/comunity/service/BoardService.java#L107

changeTitle, changeContent, changeCategory 를 하나의 Board.change() 메서드로 구현하는게 좋을 것 같아요.

**Comment by sjsage522** [comment]
리팩토링 완료했습니다.
