### ISSUE TITLE
파일 저장위치 위치 수정

### ISSUE THREAD

**Issue by LeeSM0518** [sjsage522/comunity#5]
https://github.com/sjsage522/comunity/blob/bd4a4cdeab2134d95b80fc4cf789dde1b727f326/src/main/java/com/example/comunity/util/FileUtils.java#L24

파일 저장 위치를 유연하게 받을 수 있도록 코드 수정해주세요.
ex) properties 활용, program argument 활용, ...

**Comment by sjsage522** [comment]
서버에 파일을 저장하는 경로를 정한건데 동적으로 굳이 안해도될거같았어요.

FileController 클래스의 fileDownload 메소드 내부 로직을 보시면 될거같습니당
